vti_encoding:SR|utf8-nl
vti_author:SR|IUSR_EAGLE
vti_modifiedby:SR|IUSR_EAGLE
vti_timecreated:TR|10 Jul 2000 09:33:39 -0000
vti_timelastmodified:TR|10 Jul 2000 09:34:03 -0000
vti_filesize:IR|264
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=windows-1252 GENERATOR Microsoft\\ FrontPage\\ 4.0 ProgId FrontPage.Editor.Document
vti_progid:SR|FrontPage.Editor.Document
vti_generator:SR|Microsoft FrontPage 4.0
vti_extenderversion:SR|4.0.2.2717
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|10 Jul 2000 09:33:39 -0000
vti_syncwith_raven\:80/www.dropzone.co.za:TR|10 Jul 2000 09:34:03 -0000
