vti_encoding:SR|utf8-nl
vti_author:SR|IUSR_EAGLE
vti_modifiedby:SR|IUSR_EAGLE
vti_timecreated:TR|15 May 2000 12:13:29 -0000
vti_timelastmodified:TR|10 Jul 2000 09:11:38 -0000
vti_backlinkinfo:VX|
vti_extenderversion:SR|4.0.2.2717
vti_syncwith_www.dropzone.co.za\:80/dev.dropzone.co.za:TR|15 May 2000 12:13:29 -0000
vti_syncwith_raven\:80/www.dropzone.co.za:TR|10 Jul 2000 09:11:38 -0000
vti_nexttolasttimemodified:TR|15 May 2000 12:13:29 -0000
